### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by sytone** [LumosLovegood/obsidian-mstodo-sync#2]
I was thinking about a plugin for MS Todo and came across this, looks like you are actively working on it. Are you open to a PR to add localization so it can be in English and Chinese?

**Comment by sytone** [comment]
ok, working on https://github.com/sytone/obsidian-mstodo-sync/tree/sytone/issue2 to play with localization, update the settings a bit to make localization simpler, added logging and started to play with the tracking of created tasks to see if adding a block link with an internal ID allows updating of an existing task in To Do

**Comment by LumosLovegood** [comment]
Much thanks for the efforts to make the plugin more complete!
I viewed the changes you made, they're awesome and worth learning. However, it may take some time to understand them for me.
It's my pleasure that my incomplete plugin could be found and improved. I will keep working on it.
Thanks again and look forward to your shining changes on this plugin!

**Comment by sytone** [comment]
stripped it down to basics. PR incoming.

**Comment by LumosLovegood** [comment]
> - Added a new menu command to Open To Do in a browser based on the stored task ID using the blocklink as a lookup.

Hello @sytone , It just hit me whether it's possible to Open To Do in the desktop Todo App directly using URI Schemes. Just like: 
```
ms-todo://
```
it takes effect to open the desktop app, but I don't know what the remaining paths, flags 
 or parameters should be to locate the specific resource.

something I found maybe relevant: 
[https://learn.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app](https://learn.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app)
[https://learn.microsoft.com/en-us/search/?terms=ms-todo%20uri%20schemes](https://learn.microsoft.com/en-us/search/?terms=ms-todo%20uri%20schemes)

**Comment by LumosLovegood** [comment]
Oh, get it. Just replace `https://to-do.live.com/` with `ms-todo://` is OK...

**Comment by sytone** [comment]
Could add that as an option and then change the prefix when running the command based off the toggle setting.

**Comment by sytone** [comment]
Closing up as localization and choice of protocol handler is added.
